extends: default

ignore: |
  .git/
  .venv/
  .agent/
  **/templates/db-secret.yaml

rules:
  line-length:
    max: 120
    level: warning
  braces:
    max-spaces-inside: 1
  document-start: disable

  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
