apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{include "voting-app.fullname" .}}-db'
  labels:
    app: '{{include "voting-app.name" .}}-db'
spec:
  replicas: {{.Values.replicaCounts.db}}
  selector:
    matchLabels:
      app: '{{include "voting-app.name" .}}-db'
  template:
    metadata:
      labels:
        app: '{{include "voting-app.name" .}}-db'
    spec:
      containers:
        - name: db
          image: '{{.Values.images.db}}'
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: '{{include "voting-app.fullname" .}}-db-secret'
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{include "voting-app.fullname" .}}-db-secret'
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: db-data
              mountPath: '{{.Values.db.persistence.mountPath}}'
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: '{{include "voting-app.fullname" .}}-db-data'
