apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{include "voting-app.fullname" .}}-db-data'
spec:
  accessModes:
    {{- toYaml .Values.db.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: '{{.Values.db.persistence.size}}'
  storageClassName: '{{.Values.db.persistence.storageClassName}}'
