{{- $secretName := printf "%s-db-secret" (include "voting-app.fullname" .) -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $password := randAlphaNum 32 -}}
{{- if and $secret $secret.data (hasKey $secret.data "POSTGRES_PASSWORD") -}}
{{- $password = index $secret.data "POSTGRES_PASSWORD" | b64dec -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
type: Opaque
stringData:
  POSTGRES_USER: '{{.Values.db.secret.user | default "postgres" | quote}}'
  POSTGRES_PASSWORD: {{ $password | quote }}
