apiVersion: v1
kind: Service
metadata:
  name: '{{include "voting-app.fullname" .}}-redis'
  labels:
    app: '{{include "voting-app.name" .}}-redis'
spec:
  ports:
    - port: {{.Values.service.redis.port}}
      targetPort: 6379
      name: redis
  selector:
    app: '{{include "voting-app.name" .}}-redis'
