# Prod overrides
replicaCounts:
  vote: 2
  worker: 2
  db: 1
  redis: 2

images:
  vote: dockersamples/examplevotingapp_vote:before
  worker: dockersamples/examplevotingapp_worker
  db: postgres:15-alpine
  redis: redis:alpine

service:
  vote:
    type: ClusterIP
    port: 80
  db:
    port: 5432
  redis:
    port: 6379

db:
  secret:
    user: postgres
    password: xxxxx # placeholder

env:
  POSTGRES_PORT: "5432"
