# Base values used for all environments
replicaCounts:
  vote: 2
  worker: 1
  db: 1
  redis: 1

images:
  vote: dockersamples/examplevotingapp_vote:before
  worker: dockersamples/examplevotingapp_worker
  db: postgres:15-alpine
  redis: redis:alpine

service:
  vote:
    type: ClusterIP
    port: 80
  db:
    port: 5432
  redis:
    port: 6379

resources: {}

env:
  dev:
    db:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: "5432"
    worker:
      POSTGRES_PORT: "5432"
    result:
      POSTGRES_PORT: "5432"
  prod: {}
