apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "5.0.0"
    helm:
      values: |
        server:
          service:
            type: NodePort
            nodePort: 30085
            ports:
              - name: https
                port: 8085
                targetPort: 443
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
