apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluedops-set
  namespace: argocd
spec:
  # goTemplate: true
  generators:
    - list:
        elements:
          - env: dev
            namespace: cluedops-dev
            appName: cluedops
          - env: prod
            namespace: cluedops-prod
            appName: cluedops
  template:
    metadata:
      name: '{{ .appName }}-{{ .env }}'
      labels:
        app.kubernetes.io/part-of: cluedops
        app.kubernetes.io/component: gitops
        environment: '{{ .env }}'
    spec:
      project: default
      source:
        repoURL: git@github.com:simoneroselli/cluedops.git
        targetRevision: HEAD
        path: apps/base/voting-app
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
